import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Notion | AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="h-screen overflow-hidden">
          {/* Fixed Navbar */}
          <div className="relative">
            <Header />
          </div>

          <div className="flex h-[calc(100vh-4rem)]">
            {/* Fixed Sidebar */}
            <div className="sticky top-0 h-full">
              <Sidebar />
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 p-4 bg-gray-100 overflow-y-auto">
              {children}
            </div>
          </div>

          {/* Notifications */}
          <Toaster position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}
